require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/criteria", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Criterium. As you add validations to Criterium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {scale: "Scale1", name: "Name1"} }
  let(:invalid_attributes) { {scale: "", name: ""} }

  describe "GET /index" do
    it "renders a successful response" do
      Criterium.create! valid_attributes
      get criteria_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      criterium = Criterium.create! valid_attributes
      get criterium_url(criterium)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_criterium_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      criterium = Criterium.create! valid_attributes
      get edit_criterium_url(criterium)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Criterium" do
        expect {
          post criteria_url, params: { criterium: valid_attributes }
        }.to change(Criterium, :count).by(1)
      end

      it "redirects to the created criterium" do
        post criteria_url, params: { criterium: valid_attributes }
        expect(response).to redirect_to(criterium_url(Criterium.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Criterium" do
        expect {
          post criteria_url, params: { criterium: invalid_attributes }
        }.to change(Criterium, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post criteria_url, params: { criterium: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) { {scale: "NewScale", name: "NewName"} }

      it "updates the requested criterium" do
        criterium = Criterium.create! valid_attributes
        patch criterium_url(criterium), params: { criterium: new_attributes }
        criterium.reload
        expect(criterium.name).to eq(new_attributes[:name])
        expect(criterium.scale).to eq(new_attributes[:scale])
      end

      it "redirects to the criterium" do
        criterium = Criterium.create! valid_attributes
        patch criterium_url(criterium), params: { criterium: new_attributes }
        criterium.reload
        expect(response).to redirect_to(criterium_url(criterium))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        criterium = Criterium.create! valid_attributes
        patch criterium_url(criterium), params: { criterium: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end

    context "with same parameters" do
      let(:more_valid_attributes) { {scale: "Scale1", name: "Name2"} }
      let(:same_attributes) { {scale: "Scale1", name: "Name1"} }

      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        Criterium.create! valid_attributes
        criterium = Criterium.create! more_valid_attributes
        patch criterium_url(criterium), params: { criterium: same_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested criterium" do
      criterium = Criterium.create! valid_attributes
      expect {
        delete criterium_url(criterium)
      }.to change(Criterium, :count).by(-1)
    end

    it "redirects to the criteria list" do
      criterium = Criterium.create! valid_attributes
      delete criterium_url(criterium)
      expect(response).to redirect_to(criteria_url)
    end
  end
end
